# Matemáticas Fundamentales: Lógica, Conjuntos, Funciones & Álgebra Lineal
## Guía Completa de Estudio para Temas del Examen

**Temas cubiertos:**
1. Lógica & Equivalencias Lógicas
2. Teoría de Conjuntos & Relaciones
3. Funciones: Inyectiva, Sobreyectiva, Biyectiva
4. Matrices & Sistemas de Ecuaciones
5. Determinantes
6. Valores Propios & Vectores Propios
7. Diagonalización de Matrices
8. Matrices Simétricas & Propiedades

Cada sección incluye:
- Explicaciones claras
- Ejemplos de código ejecutable
- Problemas de práctica
- Preguntas en estilo de examen

---
# PARTE 1: LÓGICA & EQUIVALENCIAS LÓGICAS

## 1.1 Proposiciones y Operadores Básicos

Una **proposición** es una afirmación que es VERDADERA o FALSA.

**Operadores básicos:**
- p ∧ q (Y): VERDADERO solo si ambos son VERDADEROS
- p ∨ q (O): VERDADERO si al menos uno es VERDADERO
- ¬p (NO): opuesto de p
- p → q (IMPLICA): FALSO solo cuando p es VERDADERO y q es FALSO
- p ↔ q (SI Y SOLO SI): VERDADERO cuando p y q tienen el mismo valor de verdad

In [ ]:
# Tabla de verdad para operadores básicos
print("Operadores Lógicos Básicos:")
print()
print("p | q | p∧q | p∨q | ¬p | p→q | p↔q")
print("-" * 45)
for p in [True, False]:
    for q in [True, False]:
        and_op = p and q
        or_op = p or q
        not_p = not p
        implies = (not p) or q
        iff = p == q
        
        print(
            f"{str(p)[0]} | {str(q)[0]} | "
            f"{str(and_op)[0]:3} | "
            f"{str(or_op)[0]:3} | "
            f"{str(not_p)[0]:2} | "
            f"{str(implies)[0]:3} | "
            f"{str(iff)[0]:3}"
        )

print()
print("Hecho clave: p → q es FALSO solo cuando p=V y q=F")
print("¡Este es el ÚNICO caso falso!")

Operadores Lógicos Básicos:

p | q | p∧q | p∨q | ¬p | p→q | p↔q
---------------------------------------------
T | T | T   | T   | F  | T   | T  
T | F | F   | T   | F  | F   | F  
F | T | F   | T   | T  | T   | F  
F | F | F   | F   | T  | T   | T  

Hecho clave: p → q es FALSO solo cuando p=V y q=F
¡Este es el ÚNICO caso falso!


## 1.2 Equivalencias Lógicas Importantes

Estas son cruciales para P6 y P14:

**Equivalencia de implicación:**
$$p \rightarrow q \equiv \neg p \vee q$$

**Negación de implicación:**
$$\neg(p \rightarrow q) \equiv p \wedge \neg q$$

**Leyes de De Morgan:**
$$\neg(p \vee q) \equiv \neg p \wedge \neg q$$
$$\neg(p \wedge q) \equiv \neg p \vee \neg q$$

**Contraposición (¡lo más importante!):**
$$p \rightarrow q \equiv \neg q \rightarrow \neg p$$

**Doble negación:**
$$\neg(\neg p) \equiv p$$


In [2]:
print("EQUIVALENCIA 1: p → q ≡ ¬p ∨ q")
print()
print("p | q | p→q | ¬p∨q | ¿Igual?")
print("-" * 35)
for p in [True, False]:
    for q in [True, False]:
        impl = (not p) or q
        neg_or = (not p) or q
        match = "✓" if impl == neg_or else "✗"
        print(f"{str(p)[0]} | {str(q)[0]} | {str(impl)[0]:3} | {str(neg_or)[0]:4} | {match}")

print()
print("EQUIVALENCIA 2: Contraposición (p→q) ≡ (¬q→¬p)")
print()
print("p | q | p→q | ¬q→¬p | ¿Igual?")
print("-" * 37)
for p in [True, False]:
    for q in [True, False]:
        impl = (not p) or q
        contrapositive = (not (not q)) or (not p)  # ¬q → ¬p
        match = "✓" if impl == contrapositive else "✗"
        print(f"{str(p)[0]} | {str(q)[0]} | {str(impl)[0]:3} | {str(contrapositive)[0]:6} | {match}")

print()
print("EQUIVALENCIA 3: Leyes de De Morgan")
print()
print("p | q | ¬(p∨q) | (¬p∧¬q) | ¿Igual?")
print("-" * 38)
for p in [True, False]:
    for q in [True, False]:
        left = not (p or q)
        right = (not p) and (not q)
        match = "✓" if left == right else "✗"
        print(f"{str(p)[0]} | {str(q)[0]} | {str(left)[0]:7} | {str(right)[0]:7} | {match}")

EQUIVALENCIA 1: p → q ≡ ¬p ∨ q

p | q | p→q | ¬p∨q | ¿Igual?
-----------------------------------
T | T | T   | T    | ✓
T | F | F   | F    | ✓
F | T | T   | T    | ✓
F | F | T   | T    | ✓

EQUIVALENCIA 2: Contraposición (p→q) ≡ (¬q→¬p)

p | q | p→q | ¬q→¬p | ¿Igual?
-------------------------------------
T | T | T   | T      | ✓
T | F | F   | F      | ✓
F | T | T   | T      | ✓
F | F | T   | T      | ✓

EQUIVALENCIA 3: Leyes de De Morgan

p | q | ¬(p∨q) | (¬p∧¬q) | ¿Igual?
--------------------------------------
T | T | F       | F       | ✓
T | F | F       | F       | ✓
F | T | F       | F       | ✓
F | F | T       | T       | ✓


## 1.3 Práctica del Examen: Equivalencias Lógicas

**Estilo P6:** Si p → q es equivalente a... ¿cuál de estas es correcta?

**Estilo P14:** ¬p → q es equivalente a...

In [3]:
print("PROBLEMA DEL EXAMEN: ¬p → q es equivalente a ¿cuál de estas?")
print()
print("A) p ∨ q")
print("B) p ∧ ¬q")
print("C) p ∨ q")
print("D) ¬p ∨ q")
print()
print("Solución:")
print("¬p → q es equivalente a ¬(¬p) ∨ q (usa la regla de implicación)")
print("                      = p ∨ q (doble negación)")
print()
print("Respuesta: A o C (son lo mismo)")
print()
print("Verificación:")
print()
print("p | q | ¬p→q | p∨q | ¿Coincide?")
print("-" * 31)
for p in [True, False]:
    for q in [True, False]:
        neg_p_implies_q = (not (not p)) or q  # ¬p → q = ¬(¬p) ∨ q
        p_or_q = p or q
        match = "✓" if neg_p_implies_q == p_or_q else "✗"
        print(f"{str(p)[0]} | {str(q)[0]} | {str(neg_p_implies_q)[0]:5} | {str(p_or_q)[0]:3} | {match}")

PROBLEMA DEL EXAMEN: ¬p → q es equivalente a ¿cuál de estas?

A) p ∨ q
B) p ∧ ¬q
C) p ∨ q
D) ¬p ∨ q

Solución:
¬p → q es equivalente a ¬(¬p) ∨ q (usa la regla de implicación)
                      = p ∨ q (doble negación)

Respuesta: A o C (son lo mismo)

Verificación:

p | q | ¬p→q | p∨q | ¿Coincide?
-------------------------------
T | T | T     | T   | ✓
T | F | T     | T   | ✓
F | T | T     | T   | ✓
F | F | F     | F   | ✓


---
# PARTE 2: CONJUNTOS, RELACIONES & FUNCIONES

## 2.1 Conceptos Básicos de Conjuntos

Un **conjunto** es una colección de elementos distintos.

**Notación:**
- A = {1, 2, 3} - conjunto con 3 elementos
- |A| = 3 - cardinalidad (tamaño) de A
- A ⊂ B - A es un subconjunto propio de B (A está en B, pero no son iguales)
- A ⊆ B - A es un subconjunto de B (podría ser igual)

In [4]:
# Conjuntos en Python
A = {1, 2, 3}
B = {1, 2, 3, 4, 5}

print(f"A = {A}")
print(f"B = {B}")
print(f"|A| = {len(A)}")
print(f"|B| = {len(B)}")
print()
print(f"A ⊂ B (A es subconjunto propio de B): {A < B}")
print(f"A ⊆ B (A es subconjunto de B): {A <= B}")
print(f"Condición: A < B significa |A| < |B|: {len(A) < len(B)}")

A = {1, 2, 3}
B = {1, 2, 3, 4, 5}
|A| = 3
|B| = 5

A ⊂ B (A es subconjunto propio de B): True
A ⊆ B (A es subconjunto de B): True
Condición: A < B significa |A| < |B|: True


## 2.2 Funciones: Inyectiva, Sobreyectiva, Biyectiva

Una **función** f: A → B asigna a cada elemento de A exactamente un elemento de B.

**Inyectiva (uno a uno):**
Si f(a₁) = f(a₂), entonces a₁ = a₂  
Cada salida proviene de como máximo una entrada.

**Sobreyectiva (sobre):**
Cada elemento de B tiene al menos una preimagen en A.  
Cada salida es "alcanzada" por alguna entrada.

**Biyectiva:**
Tanto inyectiva como sobreyectiva.  
Correspondencia perfecta uno a uno.

**Perspectiva clave para P3:**
Si A ⊂ B (lo que significa |A| < |B|), entonces:
- f: A → B NO PUEDE ser sobreyectiva (no hay suficientes entradas para alcanzar todas las salidas)
- f: A → B PUEDE ser inyectiva (diferentes entradas pueden mapear a diferentes salidas)
- f: A → B PUEDE ser inyectiva pero NO sobreyectiva

In [5]:
print("ANÁLISIS DEL EXAMEN P3:")
print()
print("Dado: A ⊂ B (A es subconjunto propio), f: A → B")
print()
print("Lo que sabemos:")
print(f"  |A| < |B| (A tiene menos elementos que B)")
print()
print("Pregunta: ¿Cuál de estas afirmaciones es verdadera?")
print()
print("A) f debe ser inyectiva")
print("   Respuesta: FALSO - f podría mapear diferentes elementos de A al mismo elemento en B")
print()
print("B) f no puede ser sobreyectiva")
print("   Respuesta: VERDADERO - no tenemos suficientes entradas en A para alcanzar todas las salidas en B")
print("   (|A| < |B| significa imposible ser sobreyectiva)")
print()
print("C) f puede ser sobreyectiva")
print("   Respuesta: FALSO - ver B arriba")
print()
print("D) f no puede ser inyectiva")
print("   Respuesta: FALSO - f puede ser inyectiva (uno a uno)")
print()
print("RESPUESTA CORRECTA: B")
print()
print("\nEjemplo para verificar:")
A = {1, 2, 3}
B = {1, 2, 3, 4, 5}

# Función: 1→1, 2→2, 3→3
f_injective = {1: 1, 2: 2, 3: 3}
print(f"\nA = {A}, |A| = {len(A)}")
print(f"B = {B}, |B| = {len(B)}")
print()
print(f"Función f (inyectiva pero no sobreyectiva):")
for a, b in f_injective.items():
    print(f"  f({a}) = {b}")
print()
print("Análisis:")
print(f"  ¿Es inyectiva? Sí (todas las salidas diferentes)")
print(f"  ¿Es sobreyectiva? No (elementos 4,5 nunca se mapean)")
print(f"  ¿Puede ser biyectiva? No (imposible cuando |A| < |B|)")

ANÁLISIS DEL EXAMEN P3:

Dado: A ⊂ B (A es subconjunto propio), f: A → B

Lo que sabemos:
  |A| < |B| (A tiene menos elementos que B)

Pregunta: ¿Cuál de estas afirmaciones es verdadera?

A) f debe ser inyectiva
   Respuesta: FALSO - f podría mapear diferentes elementos de A al mismo elemento en B

B) f no puede ser sobreyectiva
   Respuesta: VERDADERO - no tenemos suficientes entradas en A para alcanzar todas las salidas en B
   (|A| < |B| significa imposible ser sobreyectiva)

C) f puede ser sobreyectiva
   Respuesta: FALSO - ver B arriba

D) f no puede ser inyectiva
   Respuesta: FALSO - f puede ser inyectiva (uno a uno)

RESPUESTA CORRECTA: B


Ejemplo para verificar:

A = {1, 2, 3}, |A| = 3
B = {1, 2, 3, 4, 5}, |B| = 5

Función f (inyectiva pero no sobreyectiva):
  f(1) = 1
  f(2) = 2
  f(3) = 3

Análisis:
  ¿Es inyectiva? Sí (todas las salidas diferentes)
  ¿Es sobreyectiva? No (elementos 4,5 nunca se mapean)
  ¿Puede ser biyectiva? No (imposible cuando |A| < |B|)


---
# PARTE 3: MATRICES & SISTEMAS

## 3.1 Conceptos Básicos de Matrices

Una **matriz** es una cuadrícula rectangular de números.

Una **matriz cuadrada** tiene el mismo número de filas y columnas (n × n).

**Matriz simétrica:** A = A^T (igual a su transpuesta)

**Propiedades de matrices invertibles (det(A) ≠ 0):**
- La matriz es cuadrada
- El sistema Ax = b tiene una solución única
- La matriz tiene rango completo
- Los valores propios son todos distintos de cero

In [6]:
import numpy as np

print("Conceptos de Matrices:")
print()

# Matriz de ejemplo
A = np.array([
    [1, 0],
    [0, 1]
])

print(f"Matriz A (2×2):")
print(A)
print()
print(f"det(A) = {np.linalg.det(A)}")
print(f"¿Es invertible? {abs(np.linalg.det(A)) > 0.0001}")
print()

# Matriz simétrica
S = np.array([
    [2, 1],
    [1, 3]
])

print(f"Matriz simétrica S:")
print(S)
print()
print(f"S^T (transpuesta):")
print(S.T)
print()
print(f"¿Es S simétrica? {np.allclose(S, S.T)}")
print()
print(f"det(S) = {np.linalg.det(S):.4f}")
print(f"¿Es invertible? {abs(np.linalg.det(S)) > 0.0001}")

Conceptos de Matrices:

Matriz A (2×2):
[[1 0]
 [0 1]]

det(A) = 1.0
¿Es invertible? True

Matriz simétrica S:
[[2 1]
 [1 3]]

S^T (transpuesta):
[[2 1]
 [1 3]]

¿Es S simétrica? True

det(S) = 5.0000
¿Es invertible? True


## 3.2 Determinante

El **determinante** (det(A)) es un número único que nos dice sobre la matriz.

**Para matriz 2×2:**
$$A = \begin{pmatrix} a & b \\ c & d \end{pmatrix}, \quad det(A) = ad - bc$$

**Para matriz 3×3:**
$$A = \begin{pmatrix} a & b & c \\ d & e & f \\ g & h & i \end{pmatrix}$$
Usa expansión por cofactores o la regla de Sarrus.

**Propiedades clave:**
- det(A) ≠ 0 ⇒ A es invertible
- det(A) = 0 ⇒ A es singular (no invertible)
- det(A) = det(A^T)
- det(AB) = det(A) × det(B)
- det(A^(-1)) = 1/det(A)

In [7]:
print("Calculando Determinantes:")
print()

print("Ejemplo 1: Matriz 2×2")
A = np.array([
    [3, 2],
    [1, 4]
])
print(f"A = ")
print(A)
print()
print(f"det(A) = 3(4) - 2(1) = 12 - 2 = 10")
print(f"Calculado: {np.linalg.det(A):.1f}")
print()

print("Ejemplo 2: Matriz 2×2 con determinante = 0")
B = np.array([
    [2, 4],
    [1, 2]
])
print(f"B = ")
print(B)
print()
print(f"det(B) = 2(2) - 4(1) = 4 - 4 = 0")
print(f"Calculado: {np.linalg.det(B):.4f}")
print()
print(f"¿Es B invertible? No (det = 0)")
print(f"¿Por qué? Fila 2 es 0.5 × Fila 1 (filas dependientes)")
print()

print("Ejemplo 3: Matriz Simétrica 3×3")
C = np.array([
    [1, 0, 0],
    [0, 2, 0],
    [0, 0, 3]
])
print(f"C = ")
print(C)
print()
print(f"det(C) = 1 × 2 × 3 = 6 (matriz diagonal)")
print(f"Calculado: {np.linalg.det(C):.1f}")
print()
print(f"¿Es C invertible? Sí (det ≠ 0)")

Calculando Determinantes:

Ejemplo 1: Matriz 2×2
A = 
[[3 2]
 [1 4]]

det(A) = 3(4) - 2(1) = 12 - 2 = 10
Calculado: 10.0

Ejemplo 2: Matriz 2×2 con determinante = 0
B = 
[[2 4]
 [1 2]]

det(B) = 2(2) - 4(1) = 4 - 4 = 0
Calculado: 0.0000

¿Es B invertible? No (det = 0)
¿Por qué? Fila 2 es 0.5 × Fila 1 (filas dependientes)

Ejemplo 3: Matriz Simétrica 3×3
C = 
[[1 0 0]
 [0 2 0]
 [0 0 3]]

det(C) = 1 × 2 × 3 = 6 (matriz diagonal)
Calculado: 6.0

¿Es C invertible? Sí (det ≠ 0)


---
# PARTE 4: VALORES PROPIOS & VECTORES PROPIOS

## 4.1 ¿Qué son los Valores Propios y Vectores Propios?

Un **vector propio** v de la matriz A es un vector especial que no cambia de dirección cuando se multiplica por A.

Un **valor propio** λ muestra cuánto se estira el vector propio:
$$Av = \lambda v$$

**Interpretación:**
- λ > 1: El vector crece en esa dirección
- λ = 1: El vector permanece igual
- 0 < λ < 1: El vector se encoge
- λ = 0: El vector se mapea a cero
- λ < 0: El vector cambia de dirección

**Para matrices simétricas (A = A^T):**
- TODOS los valores propios son REALES (no complejos)
- Los vectores propios son ortogonales
- La matriz siempre es diagonalizable

In [ ]:
import numpy as np

print("Entendiendo Valores Propios y Vectores Propios:")
print()
print("Si A es una matriz 2×2 y v es un vector propio con valor propio λ:")
print("  A @ v = λ @ v")
print()
print("Ejemplo:")
A = np.array([
    [3, 0],
    [0, 2]
])

print(f"A = ")
print(A)
print()

eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"Valores propios: {eigenvalues}")
print(f"Vectores propios (como columnas):")
print(eigenvectors)
print()

for i, (lam, vec) in enumerate(zip(eigenvalues, eigenvectors.T)):
    print(f"Valor propio λ_{i+1} = {lam}")
    print(f"Vector propio v_{i+1} = {vec}")
    
    # Verificar A @ v = λ @ v
    Av = A @ vec
    lambda_v = lam * vec
    print(f"  A @ v = {Av}")
    print(f"  λ @ v = {lambda_v}")
    print(f"  ¿Correcto? {np.allclose(Av, lambda_v)} ✓")
    print()

## 4.2 Encontrando Valores Propios

**Paso 1:** Resuelve la ecuación característica:
$$det(A - \lambda I) = 0$$

**Paso 2:** Las soluciones son los valores propios λ

**Paso 3:** Para cada λ, resuelve (A - λI)v = 0 para encontrar vectores propios

**Para matriz diagonal 2×2:**
$$A = \begin{pmatrix} a & 0 \\ 0 & b \end{pmatrix} \quad \Rightarrow \quad \lambda_1 = a, \lambda_2 = b$$

**Para matriz simétrica 2×2:**
$$A = \begin{pmatrix} a & b \\ b & c \end{pmatrix}$$
Ambos valores propios son reales.

In [8]:
print("Encontrando Valores Propios:")
print()

print("Caso 1: Matriz diagonal (fácil)")
A = np.array([
    [5, 0],
    [0, 3]
])
print(f"A = ")
print(A)
print()
print(f"Valores propios: ¡Solo la diagonal! λ₁ = 5, λ₂ = 3")
print(f"Verificado: {np.linalg.eigvals(A)}")
print()

print("Caso 2: Matriz simétrica (ecuación característica)")
A = np.array([
    [2, 1],
    [1, 2]
])
print(f"A = ")
print(A)
print()
print(f"Resuelve det(A - λI) = 0:")
print(f"  det([[2-λ, 1], [1, 2-λ]]) = 0")
print(f"  (2-λ)² - 1 = 0")
print(f"  4 - 4λ + λ² - 1 = 0")
print(f"  λ² - 4λ + 3 = 0")
print(f"  (λ - 1)(λ - 3) = 0")
print(f"  λ₁ = 1, λ₂ = 3")
print()
print(f"Verificado: {sorted(np.linalg.eigvals(A))}")

Encontrando Valores Propios:

Caso 1: Matriz diagonal (fácil)
A = 
[[5 0]
 [0 3]]

Valores propios: ¡Solo la diagonal! λ₁ = 5, λ₂ = 3
Verificado: [5. 3.]

Caso 2: Matriz simétrica (ecuación característica)
A = 
[[2 1]
 [1 2]]

Resuelve det(A - λI) = 0:
  det([[2-λ, 1], [1, 2-λ]]) = 0
  (2-λ)² - 1 = 0
  4 - 4λ + λ² - 1 = 0
  λ² - 4λ + 3 = 0
  (λ - 1)(λ - 3) = 0
  λ₁ = 1, λ₂ = 3

Verificado: [np.float64(1.0), np.float64(3.0)]


## 4.3 Propiedades de Matrices Simétricas

**Para cualquier matriz simétrica A (donde A = A^T):**

1. **Todos los valores propios son REALES** (no complejos)
2. **La matriz siempre es diagonalizable**
3. **Los vectores propios son ortogonales** (perpendiculares)
4. **Suma de valores propios = traza(A)** = suma de elementos diagonales
5. **Producto de valores propios = det(A)**
6. **A puede escribirse como A = PDP^T** donde D es diagonal (diagonalización)

**Traza (suma de la diagonal):**
$$\text{trace}(A) = \sum_{i} A_{ii} = \sum_{i} \lambda_i$$

In [ ]:
print("Propiedades de Matrices Simétricas:")
print()

A = np.array([
    [4, 1],
    [1, 3]
])

print(f"A = ")
print(A)
print(f"\nA^T = ")
print(A.T)
print(f"¿Es simétrica? {np.allclose(A, A.T)} ✓")
print()

eigenvalues = np.linalg.eigvals(A)
print(f"Valores propios: {eigenvalues}")
print(f"¿Todos reales? {all(np.isreal(eigenvalues))} ✓")
print()

trace_A = np.trace(A)
sum_eigenvalues = np.sum(eigenvalues)
print(f"Propiedad 1: Suma de valores propios = traza(A)")
print(f"  traza(A) = 4 + 3 = {trace_A}")
print(f"  suma(λ) = {sum_eigenvalues:.4f}")
print(f"  ¿Iguales? {np.isclose(trace_A, sum_eigenvalues)} ✓")
print()

det_A = np.linalg.det(A)
prod_eigenvalues = np.prod(eigenvalues)
print(f"Propiedad 2: Producto de valores propios = det(A)")
print(f"  det(A) = {det_A:.4f}")
print(f"  prod(λ) = {prod_eigenvalues:.4f}")
print(f"  ¿Iguales? {np.isclose(det_A, prod_eigenvalues)} ✓")
print()

print(f"Propiedad 3: La matriz es diagonalizable")
print(f"  Podemos escribir A = PDP^T")
print(f"  donde D = matriz diagonal de valores propios")
print(f"  donde P = matriz de vectores propios")

## 4.4 Ejemplo de Pregunta del Examen (Estilo P10, P18)

"Dada una matriz simétrica 3×3 con todos los valores propios negativos. Encuentra: ¿es diagonalizable? ¿Cuál es la suma de los valores propios?"

In [ ]:
print("PREGUNTA DEL EXAMEN (Estilo P10/P18):")
print()
print("Dado: A es una matriz simétrica 3×3")
print("Todos los valores propios son negativos.")
print()
print("Preguntas:")
print("a) ¿Es A diagonalizable?")
print("   Respuesta: SÍ - Todas las matrices simétricas son diagonalizable ✓")
print()
print("b) ¿Qué hay de los valores propios?")
print("   Respuesta: Son REALES y NEGATIVOS ✓")
print()
print("c) ¿Cuál es la suma de los valores propios?")
print("   Respuesta: traza(A) = suma de elementos diagonales")
print("   Si todos λᵢ < 0, entonces traza(A) < 0")
print()
print("Ejemplo:")
print()

A = np.array([
    [-1, 0, 0],
    [0, -2, 0],
    [0, 0, -3]
])

print(f"A = ")
print(A)
print()

eigenvalues = np.linalg.eigvals(A)
print(f"Valores propios: {eigenvalues}")
print(f"¿Todos negativos? {all(eigenvalues < 0)} ✓")
print()

trace_A = np.trace(A)
print(f"traza(A) = {trace_A}")
print(f"Suma de valores propios = {np.sum(eigenvalues)}")
print(f"¿Son iguales? {np.isclose(trace_A, np.sum(eigenvalues))} ✓")
print()

print(f"¿Es A diagonalizable? SÍ (matriz simétrica) ✓")

---
# PARTE 5: DIAGONALIZACIÓN DE MATRICES
## (Preguntas del Examen: P7, P18)

La diagonalización es el proceso de escribir A = PDP^(-1), lo que es muy útil para entender la estructura de la matriz.

## 5.1 ¿Qué es la Diagonalización?

**Objetivo:** Escribir una matriz A como:
$$A = PDP^{-1}$$

Donde:
- **P** = matriz con vectores propios como columnas
- **D** = matriz diagonal con valores propios en la diagonal
- **P^(-1)** = inversa de P

**Para matrices simétricas:**
$$A = PDP^T$$
(P^(-1) = P^T porque los vectores propios son ortogonales)

**Requisito para diagonalización:**
- La matriz debe tener n vectores propios linealmente independientes (para una matriz n×n)
- **Todas las matrices simétricas son diagonalizables**
- **No todas las matrices no simétricas son diagonalizables**

In [ ]:
import numpy as np

print("Proceso de Diagonalización:")
print()

A = np.array([
    [3, 1],
    [0, 2]
])

print(f"Matriz original A:")
print(A)
print()

# Encontrar valores propios y vectores propios
eigenvalues, eigenvectors = np.linalg.eig(A)

print(f"Valores propios: {eigenvalues}")
print()

print(f"Vectores propios (como columnas):")
print(eigenvectors)
print()

P = eigenvectors
D = np.diag(eigenvalues)
P_inv = np.linalg.inv(P)

print(f"P (vectores propios como columnas) = ")
print(P)
print()

print(f"D (valores propios en diagonal) = ")
print(D)
print()

print(f"P^(-1) = ")
print(P_inv)
print()

# Verificar: A = P @ D @ P_inv
A_reconstructed = P @ D @ P_inv
print(f"Verificación: P @ D @ P^(-1) = ")
print(A_reconstructed)
print()

print(f"A original = ")
print(A)
print()

print(f"¿Coinciden? {np.allclose(A, A_reconstructed)} ✓")

## 5.2 Verificando si una Matriz es Diagonalizable

**Comprobaciones rápidas:**

1. **Si A es simétrica (A = A^T):** SIEMPRE diagonalizable ✓
2. **Si A tiene n valores propios distintos:** SIEMPRE diagonalizable ✓
3. **Si A es triangular superior/inferior:** Matriz diagonal o necesita verificar valores propios repetidos
4. **Para valores propios repetidos:** Verifica si puedes encontrar suficientes vectores propios independientes

**Para tu examen (P7, P18):**
Las matrices son generalmente simétricas, así que son SIEMPRE diagonalizables.

In [ ]:
print("Verificación de Diagonalizabilidad:")
print()

print("Matriz 1: Simétrica (siempre diagonalizable)")
A1 = np.array([
    [2, 1],
    [1, 3]
])
print(f"A = ")
print(A1)
print(f"A^T = ")
print(A1.T)
print(f"¿Simétrica? {np.allclose(A1, A1.T)} ✓")
print(f"¿Diagonalizable? SÍ (todas las matrices simétricas son) ✓")
print()

print("Matriz 2: No simétrica")
A2 = np.array([
    [1, 1],
    [0, 1]
])
print(f"A = ")
print(A2)
print(f"A^T = ")
print(A2.T)
print(f"¿Simétrica? {np.allclose(A2, A2.T)}")
print()

eigenvalues = np.linalg.eigvals(A2)
print(f"Valores propios: {eigenvalues}")
print(f"¿Todos distintos? No (ambos iguales a 1)")
print(f"¿Diagonalizable? Necesita verificar número de vectores propios")
print()

# Intentar diagonalizar
try:
    _, eigenvectors = np.linalg.eig(A2)
    rank = np.linalg.matrix_rank(eigenvectors)
    print(f"Número de vectores propios independientes: {rank}")
    print(f"Necesita 2 para matriz 2×2, tiene {rank}")
    print(f"¿Diagonalizable? {rank == 2} ✗")
except:
    print("No diagonalizable ✗")

---
# PARTE 6: PROBLEMAS DE PRÁCTICA DEL EXAMEN

Aquí hay problemas en estilo de examen con soluciones completas.

## Práctica P3: Funciones

**Problema:** Sean A y B conjuntos finitos con A ⊂ B y |A| < |B|. Sea f: A → B una función.

¿Cuál afirmación es verdadera?
- A) f debe ser inyectiva
- B) f no puede ser sobreyectiva
- C) f puede ser sobreyectiva
- D) f no puede ser inyectiva

In [ ]:
print("SOLUCIÓN - Problema Estilo P3:")
print()
print("Dado: A ⊂ B, |A| < |B|, f: A → B")
print()
print("Análisis:")
print()
print("Como |A| < |B|, tenemos menos entradas que salidas.")
print()
print("A) 'f debe ser inyectiva' - FALSO")
print("   Contraejemplo: f(1)=1, f(2)=1, f(3)=1")
print("   Todos los elementos de A se mapean al mismo elemento en B")
print()
print("B) 'f no puede ser sobreyectiva' - VERDADERO ✓")
print("   Razón: Para ser sobreyectiva, cada elemento de B debe ser alcanzado.")
print("   Pero solo tenemos |A| < |B| entradas.")
print("   Principio del Palomar: imposible alcanzar todas las |B| salidas")
print()
print("C) 'f puede ser sobreyectiva' - FALSO")
print("   Esto contradice B")
print()
print("D) 'f no puede ser inyectiva' - FALSO")
print("   Contraejemplo: f(1)=1, f(2)=2, f(3)=3")
print("   Esto es inyectivo (todos diferentes)")
print()
print("RESPUESTA: B")

## Práctica P6/P14: Lógica

**Problema:** ¿A qué es equivalente ¬p → q?
- A) p ∨ q
- B) ¬p ∨ q
- C) p ∧ q
- D) ¬(p ∧ q)

In [ ]:
print("SOLUCIÓN - Problema Estilo P6/P14:")
print()
print("Problema: ¿A qué es equivalente ¬p → q?")
print()
print("Paso 1: Usa la regla de implicación: p → q ≡ ¬p ∨ q")
print()
print("Paso 2: Aplica a ¬p → q:")
print("  ¬p → q ≡ ¬(¬p) ∨ q")
print()
print("Paso 3: Aplica doble negación: ¬(¬p) = p")
print("  ≡ p ∨ q")
print()
print("RESPUESTA: A (p ∨ q)")
print()
print("Verificación con tabla de verdad:")
print()
print("p | q | ¬p | ¬p→q | p∨q | ¿Igual?")
print("-" * 40)
for p in [True, False]:
    for q in [True, False]:
        neg_p = not p
        neg_p_implies_q = (not neg_p) or q
        p_or_q = p or q
        match = "✓" if neg_p_implies_q == p_or_q else "✗"
        print(f"{str(p)[0]} | {str(q)[0]} | {str(neg_p)[0]:2} | {str(neg_p_implies_q)[0]:5} | {str(p_or_q)[0]:3} | {match}")

## Práctica P7/P10/P18: Valores Propios y Diagonalización

**Problema:** Sea A una matriz simétrica 2×2:
$$A = \begin{pmatrix} 4 & 1 \\ 1 & 3 \end{pmatrix}$$

Encuentra:
- Los valores propios
- La suma de valores propios (traza)
- ¿Es A diagonalizable?
- ¿Puede A escribirse como A = PDP^T?

In [ ]:
import numpy as np

print("SOLUCIÓN - Problema Estilo P7/P10/P18:")
print()

A = np.array([
    [4, 1],
    [1, 3]
])

print(f"Matriz A:")
print(A)
print()

print("Paso 1: Verifica si es simétrica")
print(f"A^T = ")
print(A.T)
print(f"¿Es simétrica? {np.allclose(A, A.T)} ✓")
print()

print("Paso 2: Encuentra los valores propios")
eigenvalues = np.linalg.eigvals(A)
print(f"Ecuación característica: det(A - λI) = 0")
print(f"det([[4-λ, 1], [1, 3-λ]]) = 0")
print(f"(4-λ)(3-λ) - 1 = 0")
print(f"12 - 4λ - 3λ + λ² - 1 = 0")
print(f"λ² - 7λ + 11 = 0")
print()
print(f"Valores propios: {eigenvalues}")
print(f"¿Todos reales? {all(np.isreal(eigenvalues))} ✓ (matriz simétrica)")
print()

print("Paso 3: Suma de valores propios")
trace_A = np.trace(A)
sum_eig = np.sum(eigenvalues)
print(f"traza(A) = 4 + 3 = {trace_A}")
print(f"suma(λ) = {sum_eig:.4f}")
print(f"¿Iguales? {np.isclose(trace_A, sum_eig)} ✓")
print()

print("Paso 4: ¿Diagonalizable?")
print(f"¿Es A simétrica? SÍ ✓")
print(f"Por lo tanto: A es SIEMPRE diagonalizable ✓")
print()

print("Paso 5: Diagonalización A = PDP^T")
_, eigenvectors = np.linalg.eig(A)
P = eigenvectors
D = np.diag(eigenvalues)

print(f"P (vectores propios como columnas):")
print(P)
print()
print(f"D (valores propios en diagonal):")
print(D)
print()

A_reconstructed = P @ D @ P.T
print(f"Verificación: P @ D @ P^T = ")
print(A_reconstructed)
print()
print(f"A original:")
print(A)
print()
print(f"¿Coinciden? {np.allclose(A, A_reconstructed)} ✓")
print()
print("RESPUESTAS:")
print(f"1. Valores propios: {eigenvalues[0]:.4f}, {eigenvalues[1]:.4f}")
print(f"2. Suma: {trace_A}")
print(f"3. ¿Diagonalizable? SÍ")
print(f"4. ¿Puede escribirse A = PDP^T? SÍ")

## Práctica P11: Determinante e Invertibilidad

**Problema:** Dada una matriz 2×2 con determinante ≠ 0. ¿Cuál de estas afirmaciones es verdadera?
- A) La matriz es invertible
- B) Las filas son linealmente dependientes
- C) Las columnas son linealmente independientes
- D) La matriz es singular

In [ ]:
print("SOLUCIÓN - Problema Estilo P11:")
print()
print("Dado: det(A) ≠ 0")
print()
print("A) 'La matriz es invertible' - VERDADERO ✓")
print("   Hecho clave: det(A) ≠ 0 ⇔ A es invertible")
print()
print("B) 'Las filas son linealmente dependientes' - FALSO")
print("   Si det(A) ≠ 0, las filas son INDEPENDIENTES")
print()
print("C) 'Las columnas son linealmente independientes' - VERDADERO ✓")
print("   Si det(A) ≠ 0, las columnas también son INDEPENDIENTES")
print()
print("D) 'La matriz es singular' - FALSO")
print("   Singular significa det = 0, pero tenemos det ≠ 0")
print()
print("RESPUESTAS: A y C son VERDADERAS")
print()
print("Relaciones clave:")
print("  det(A) ≠ 0  ⇔  A es invertible")
print("  det(A) ≠ 0  ⇔  filas linealmente independientes")
print("  det(A) ≠ 0  ⇔  columnas linealmente independientes")
print("  det(A) ≠ 0  ⇔  rango(A) = n")
print("  det(A) ≠ 0  ⇔  Ax=b tiene solución única")

---
# RESUMEN: CONCEPTOS CLAVE PARA TU EXAMEN

## Referencia Rápida

**P3 (Funciones):**
- Si |A| < |B|, entonces f: A → B no puede ser sobreyectiva
- Pero f puede ser inyectiva

**P6, P14 (Lógica):**
- p → q ≡ ¬p ∨ q (regla de implicación)
- p → q ≡ ¬q → ¬p (contraposición)
- ¬p → q ≡ p ∨ q (doble negación + implicación)

**P7, P10, P18 (Valores Propios & Diagonalización):**
- Para matrices simétricas: TODOS los valores propios son REALES
- Para matrices simétricas: SIEMPRE diagonalizable
- suma(λ) = traza(A) (suma de la diagonal)
- prod(λ) = det(A)

**P11 (Determinante):**
- det(A) ≠ 0 ⇔ invertible
- det(A) ≠ 0 ⇔ filas/columnas independientes
- det(A) = 0 ⇔ singular (no invertible)

---
# PRÁCTICA FINAL: PROBLEMAS MIXTOS

Prueba tu comprensión con estos problemas mixtos.

In [ ]:
print("PROBLEMAS DE PRÁCTICA FINAL")
print()
print("=" * 50)
print()

print("PROBLEMA 1: Lógica")
print("¿Cuál es la contraposición de 'p → q'?")
print()
print("Solución: ¬q → ¬p")
print()
print("¿Por qué? p → q es lógicamente equivalente a ¬q → ¬p")
print()
print("=" * 50)
print()

print("PROBLEMA 2: Funciones")
print("A = {1, 2}, B = {1, 2, 3, 4}")
print("¿Es f: A → B (f(1)=1, f(2)=2) inyectiva? ¿Sobreyectiva?")
print()
print("Solución:")
print("  ¿Inyectiva? SÍ (todas las salidas diferentes)")
print("  ¿Sobreyectiva? NO (elementos 3,4 nunca se mapean)")
print()
print("=" * 50)
print()

print("PROBLEMA 3: Valores Propios")
print("A = [[2, 0], [0, 3]]")
print("Encuentra los valores propios y traza(A)")
print()
import numpy as np
A = np.array([[2, 0], [0, 3]])
eig = np.linalg.eigvals(A)
trace = np.trace(A)
print(f"Solución:")
print(f"  Valores propios: {eig}")
print(f"  traza(A) = {trace}")
print(f"  suma(λ) = {np.sum(eig)}")
print(f"  ¿Iguales? {np.isclose(trace, np.sum(eig))} ✓")
print()
print("=" * 50)
print()

print("PROBLEMA 4: Determinante")
print("A = [[1, 2], [2, 4]]")
print("¿Es A invertible?")
print()
A = np.array([[1, 2], [2, 4]])
det = np.linalg.det(A)
print(f"Solución:")
print(f"  det(A) = {det:.4f}")
print(f"  ¿Es det ≠ 0? {abs(det) > 0.0001}")
print(f"  ¿Es invertible? NO ✗")
print(f"  ¿Por qué? Fila 2 = 2 × Fila 1 (filas dependientes)")
print()
print("=" * 50)
print()

print("PROBLEMA 5: Propiedades de Matrices Simétricas")
print("A = [[3, 1], [1, 2]] (simétrica)")
print("¿Es A diagonalizable? ¿Son reales los valores propios?")
print()
A = np.array([[3, 1], [1, 2]])
eig = np.linalg.eigvals(A)
print(f"Solución:")
print(f"  ¿Es simétrica? {np.allclose(A, A.T)} ✓")
print(f"  Valores propios: {eig}")
print(f"  ¿Todos reales? {all(np.isreal(eig))} ✓")
print(f"  ¿Diagonalizable? SÍ (matriz simétrica) ✓")

---
# CONSEJOS PARA EL EXAMEN

## Antes del Examen

1. **Memoriza estas equivalencias:**
   - p → q ≡ ¬p ∨ q
   - p → q ≡ ¬q → ¬p (contraposición)

2. **Domina las propiedades de funciones:**
   - Si |A| < |B|: no puede ser sobreyectiva, puede ser inyectiva
   - Inyección necesita salidas diferentes
   - Sobreyección necesita todas las salidas alcanzadas

3. **Hechos de matrices simétricas:**
   - Todos los valores propios son REALES
   - SIEMPRE diagonalizable
   - suma(λ) = traza(A)
   - prod(λ) = det(A)

4. **Determinante clave:**
   - det(A) ≠ 0 ⇔ invertible
   - det(A) = 0 ⇔ singular

## Durante el Examen

1. **Para preguntas de lógica:** Construye tablas de verdad si no estás seguro
2. **Para preguntas de funciones:** Cuenta elementos y verifica si la sobreyección es posible
3. **Para preguntas de valores propios:** Recuerda que simétrica = real + diagonalizable
4. **Para preguntas de determinante:** det = 0 significa singular (no invertible)

## Después de Terminar Cada Pregunta

1. Verifica que tu respuesta tenga sentido
2. Para matrices: verifica A = PDP^(-1)
3. Para lógica: revisa la tabla de verdad
4. Para funciones: cuenta nuevamente

---

**¡Buena suerte en tu examen! ¡Puedes lograrlo!** 🙏